name: 'Compile rust'
description: 'Compile stump rust server'

inputs:
  platform:
    description: 'runner plaform'
    required: true

runs:
  using: composite
  steps:
    - name: Checkout project
      uses: actions/checkout@v3
    - name: Setup rust
      uses: .github/actions/setup-rust
      with:
        plaform: ${{ inputs.platform }}
    - name: Generate Prisma client
      uses: ./.github/actions/generate-prisma-client
    - name: Download frontend
      uses: actions/download-artifact@v3
      with:
        name: web
        path: ./dist
      working-directory: apps/server
    - name: Display structure of downloaded files
      run: ls -R dist
      shell: bash
      working-directory: apps/server
    - name: Build server
      shell: bash
      run: cargo build --release
