name: 'Compile Web Application'
description: 'Compile stump web'

runs:
  using: composite
  steps:
    - name: Checkout project
      uses: actions/checkout@v3
    - uses: ./.github/actions/pnpm-setup
    - name: Install dependencies
      shell: bash
      run: pnpm install
      working-directory: apps/web
    - name: Build app
      shell: bash
      run: pnpm run build
      working-directory: apps/web
