name: 'Compile Web Application'
description: 'Compile stump web client'

inputs:
  node-version:
    required: true
    description: 'Node version to use'
  node-pnpm-version:
    required: true
    description: 'Pnpm version to use'

outputs:
  dist-path:
    description: 'Path to the compiled artifact'
    value: ./apps/web

runs:
  using: composite
  steps:
    - name: Checkout project
      uses: actions/checkout@v3
    - name: Setup node 
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
    - uses: pnpm/action-setup@v2.0.1
      name: Install pnpm
      id: pnpm-install
      with:
        version: ${{ inputs.node-pnpm-version }}
        run_install: false
    - name: Get pnpm store directory
      shell: bash
      id: pnpm-cache
      run: |
        echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
    - uses: actions/cache@v3
      name: Setup pnpm cache
      with:
        path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-store-
    - name: Install dependencies
      shell: bash
      run: pnpm install
      working-directory: apps/client
    - name: TypeScript check for apps/client
      shell: bash
      run: pnpm run build 
      working-directory: apps/client
