name: "Build legacy Nix package on Ubuntu"

on:
  push:
    paths:
      - flake.nix
      - flake.lock

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v17
      - name: Building package
        run: nix develop --command "pnpm core run setup && cargo check"
