name: Stump-nightly

on:
  push:
    branches:
      - 'gh-actions'
# on:
#   schedule:
#     # * is a special character in YAML so you have to quote this string
#     - cron: '0 1 * * *'
# workflow_dispatch:

jobs:
  strategy:
    fail-fast: true
    matrix:
      plaform: [ubuntu-20.04]
  build-web:
    name: Build web application
    runs-on: ${{ matrix.plaform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build web
        uses: ./.github/actions/build-web
  build-server:
    name: Build server
    runs-on: ${{ matrix.plaform }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build server
        uses: ./.github/actions/build-server
        with:
          platform: ${{ matrix.plaform }}
      - name: Upload
        uses: ./.github/actions/upload-artifact
        working-directory: apps/server
        with:
          upload-name: server
          upload-path: release/stump_server
