name: Stump-nightly

on:
  push:
    branches: 
      - 'gh-actions'

jobs:
  build-web:
    name: Build web application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build web
        uses: ./.github/actions/build-web
      - name: Upload web build
        uses: ./.github/actions/upload-artifact
        with:
          upload-name: web-application
          upload-path: web-application
